export const TASK_SAVE_INIT = 'TASK_SAVE_INIT';
export const TASK_SAVE_SUCCESS = 'TASK_SAVE_SUCCESS';
export const TASK_SAVE_FAILURE = 'TASK_SAVE_FAILURE';

export const TASK_LIST_INIT = 'TASK_LIST_INIT';
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS';
export const TASK_LIST_FAILURE = 'TASK_LIST_FAILURE';

export const TASK_GET_BY_ID_INIT = 'TASK_GET_BY_ID_INIT';
export const TASK_GET_BY_ID_SUCCESS = 'TASK_GET_BY_ID_SUCCESS';
export const TASK_GET_BY_ID_FAILURE = 'TASK_GET_BY_ID_FAILURE';

export const TASK_REMOVE_BY_ID_INIT = 'TASK_REMOVE_BY_ID_INIT';
export const TASK_REMOVE_BY_ID_SUCCESS = 'TASK_REMOVE_BY_ID_SUCCESS';
export const TASK_REMOVE_BY_ID_FAILURE = 'TASK_REMOVE_BY_ID_FAILURE';